### ISSUE TITLE
Feature suggestion: Extend recipes package with step_geohash

### ISSUE THREAD

**Issue by jrosell** [JosiahParry/geohash#1]
I used step_mutate and other geohash libraries in the past. I wish that some package could implement a recipes extension with step_geohash step.
I assume this could add at least Suggest dependencies, so I don't know if geohash package is the place or not for this.

Let me know if I can help with it.

**Comment by JosiahParry** [comment]
That would be great! I think it could use what is outlined here: 
https://www.tidymodels.org/learn/develop/recipes/

**Comment by jrosell** [comment]
It's exactly what I was thinking of.

**Comment by JosiahParry** [comment]
If you want to create a PR with a step_geohash() and adds recipes to to `Suggests` that would be quite welcomed

**Comment by jrosell** [comment]
Today I saw that there was already a {geohash} package in CRAN (now archived) https://github.com/Ironholds/geohash/tree/master

**Comment by jrosell** [comment]
I close this issue. CRAN would be a future option for this package?

**Comment by JosiahParry** [comment]
Yes, lets close this. The package with the name `{geohash}` was pulled in 2018 which is almost 7 years ago now. I was going to ask `r-package-devel` to see what would be possible. I'd like if the name was kept!
